# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title The shortest route in the travelling salesman problem
#' @description
#' This algorithms returns the indices of towns in the shortest order for the Euclidean norm
#' @name monVoyageRcpp
#' @param towns dataframe of towns generated by the `Towns` function
#'
#' @export
monVoyageRcpp <- function(towns) {
    .Call(`_salesmanRcpp_monVoyageRcpp`, towns)
}

